import {
  LayoutDashboard, Users, GraduationCap, BookOpen, ClipboardList, FileText,
  Settings, Pill, ShoppingCart, Package, TrendingUp, UserCheck,
  CreditCard, DollarSign, Receipt, Eye, Stethoscope, Calendar,
  ClipboardCheck, AlertTriangle, Briefcase, Clock, Search, Shield, Target, Truck, BarChart3,
  UserPlus, Plane, FileWarning, FileCheck, Building2, Network, GraduationCap as Training,
  Star, Zap, ArrowUpRight, Heart, FolderOpen, MessageSquare, Clipboard, Sliders
} from "lucide-react"
import type { RoleKey } from "@/hooks/use-role"
import type { WorkspaceType } from "@/lib/supabase"

export interface NavItem {
  id: string
  label: { fr: string; en: string }
  icon: typeof LayoutDashboard
}

export interface RoleConfig {
  label: { fr: string; en: string }
  accent: string
  accentBg: string
  menu: NavItem[]
}

export const ROLE_CONFIGS: Record<WorkspaceType, Record<RoleKey, RoleConfig>> = {
  education: {
    admin: {
      label: { fr: "Administrateur", en: "Administrator" },
      accent: "text-blue-600 dark:text-blue-400",
      accentBg: "bg-blue-500",
      menu: [
        { id: "dashboard", label: { fr: "Tableau de bord", en: "Dashboard" }, icon: LayoutDashboard },
        { id: "reports", label: { fr: "Rapports", en: "Reports" }, icon: BarChart3 },
        { id: "habits", label: { fr: "Habitudes", en: "Habits" }, icon: Target },
        { id: "members", label: { fr: "Équipe", en: "Team" }, icon: UserCheck },
        { id: "security", label: { fr: "Sécurité", en: "Security" }, icon: Shield },
        { id: "settings", label: { fr: "Paramètres", en: "Settings" }, icon: Settings },
      ],
    },
    manager: {
      label: { fr: "Directeur", en: "Director" },
      accent: "text-blue-600 dark:text-blue-400",
      accentBg: "bg-blue-500",
      menu: [
        { id: "dashboard", label: { fr: "Tableau de bord", en: "Dashboard" }, icon: LayoutDashboard },
        { id: "reports", label: { fr: "Rapports", en: "Reports" }, icon: BarChart3 },
      ],
    },
    teacher: {
      label: { fr: "Enseignant", en: "Teacher" },
      accent: "text-indigo-600 dark:text-indigo-400",
      accentBg: "bg-indigo-500",
      menu: [
        { id: "dashboard", label: { fr: "Tableau de bord", en: "Dashboard" }, icon: LayoutDashboard },
        { id: "students", label: { fr: "Élèves", en: "Students" }, icon: GraduationCap },
        { id: "classes", label: { fr: "Classes", en: "Classes" }, icon: BookOpen },
        { id: "attendance", label: { fr: "Présences", en: "Attendance" }, icon: ClipboardCheck },
        { id: "grades", label: { fr: "Notes", en: "Grades" }, icon: ClipboardList },
        { id: "schedule", label: { fr: "Emplois du temps", en: "Schedule" }, icon: Calendar },
        { id: "reportCards", label: { fr: "Bulletins", en: "Report Cards" }, icon: FileText },
      ],
    },
    supervisor: {
      label: { fr: "Surveillant", en: "Supervisor" },
      accent: "text-amber-600 dark:text-amber-400",
      accentBg: "bg-amber-500",
      menu: [
        { id: "dashboard", label: { fr: "Tableau de bord", en: "Dashboard" }, icon: LayoutDashboard },
        { id: "attendance", label: { fr: "Présences", en: "Attendance" }, icon: ClipboardCheck },
        { id: "discipline", label: { fr: "Discipline", en: "Discipline" }, icon: Shield },
        { id: "incidents", label: { fr: "Incidents", en: "Incidents" }, icon: AlertTriangle },
        { id: "reportCards", label: { fr: "Bulletins", en: "Report Cards" }, icon: FileText },
      ],
    },
    cashier: {
      label: { fr: "Caissier", en: "Cashier" },
      accent: "text-emerald-600 dark:text-emerald-400",
      accentBg: "bg-emerald-500",
      menu: [
        { id: "dashboard", label: { fr: "Tableau de bord", en: "Dashboard" }, icon: LayoutDashboard },
        { id: "payments", label: { fr: "Paiements", en: "Payments" }, icon: CreditCard },
        { id: "history", label: { fr: "Historique", en: "History" }, icon: Clock },
      ],
    },
    accountant: {
      label: { fr: "Comptable", en: "Accountant" },
      accent: "text-violet-600 dark:text-violet-400",
      accentBg: "bg-violet-500",
      menu: [
        { id: "dashboard", label: { fr: "Tableau de bord", en: "Dashboard" }, icon: LayoutDashboard },
        { id: "payments", label: { fr: "Paiements", en: "Payments" }, icon: CreditCard },
        { id: "accounting", label: { fr: "Comptabilité", en: "Accounting" }, icon: DollarSign },
        { id: "reportCards", label: { fr: "Bulletins", en: "Report Cards" }, icon: FileText },
      ],
    },
    viewer: {
      label: { fr: "Observateur", en: "Observer" },
      accent: "text-slate-600 dark:text-slate-400",
      accentBg: "bg-slate-500",
      menu: [
        { id: "dashboard", label: { fr: "Tableau de bord", en: "Dashboard" }, icon: LayoutDashboard },
        { id: "students", label: { fr: "Élèves", en: "Students" }, icon: GraduationCap },
        { id: "classes", label: { fr: "Classes", en: "Classes" }, icon: BookOpen },
        { id: "reportCards", label: { fr: "Bulletins", en: "Report Cards" }, icon: FileText },
      ],
    },
    payroll: { label: { fr: "Paie", en: "Payroll" }, accent: "text-pink-600", accentBg: "bg-pink-500", menu: [] },
    hr: {
      label: { fr: "RH", en: "HR" },
      accent: "text-cyan-600",
      accentBg: "bg-cyan-500",
      menu: [
        { id: "hr_dashboard", label: { fr: "Tableau de bord RH", en: "HR Dashboard" }, icon: LayoutDashboard },
        { id: "hr_employees", label: { fr: "Employés", en: "Employees" }, icon: Users },
        { id: "hr_recruitment", label: { fr: "Recrutement", en: "Recruitment" }, icon: UserPlus },
        { id: "hr_attendance", label: { fr: "Présence", en: "Attendance" }, icon: ClipboardCheck },
        { id: "hr_leave", label: { fr: "Congés", en: "Leave" }, icon: Plane },
        { id: "hr_absences", label: { fr: "Absences", en: "Absences" }, icon: FileWarning },
        { id: "hr_contracts", label: { fr: "Contrats", en: "Contracts" }, icon: FileCheck },
        { id: "hr_departments", label: { fr: "Départements", en: "Departments" }, icon: Building2 },
        { id: "hr_orgchart", label: { fr: "Organigramme", en: "Org Chart" }, icon: Network },
        { id: "hr_training", label: { fr: "Formations", en: "Training" }, icon: Training },
        { id: "hr_evaluations", label: { fr: "Évaluations", en: "Evaluations" }, icon: Star },
        { id: "hr_skills", label: { fr: "Compétences", en: "Skills" }, icon: Zap },
        { id: "hr_promotions", label: { fr: "Promotions", en: "Promotions" }, icon: ArrowUpRight },
        { id: "hr_discipline", label: { fr: "Discipline", en: "Discipline" }, icon: Shield },
        { id: "hr_health_safety", label: { fr: "Santé et sécurité", en: "Health & Safety" }, icon: Heart },
        { id: "hr_documents", label: { fr: "Documents RH", en: "HR Documents" }, icon: FolderOpen },
        { id: "hr_communication", label: { fr: "Communication", en: "Communication" }, icon: MessageSquare },
        { id: "hr_reports", label: { fr: "Rapports", en: "Reports" }, icon: BarChart3 },
        { id: "hr_audit_log", label: { fr: "Journal d'audit", en: "Audit Log" }, icon: Clipboard },
        { id: "hr_settings", label: { fr: "Paramètres RH", en: "HR Settings" }, icon: Sliders },
      ],
    },
    stock_manager: { label: { fr: "Gestionnaire de stock", en: "Stock Manager" }, accent: "text-orange-600", accentBg: "bg-orange-500", menu: [
      { id: "dashboard", label: { fr: "Tableau de bord", en: "Dashboard" }, icon: LayoutDashboard },
      { id: "inventory", label: { fr: "Inventaire", en: "Inventory" }, icon: Package },
      { id: "orders", label: { fr: "Commandes", en: "Orders" }, icon: Truck },
      { id: "reports", label: { fr: "Rapports", en: "Reports" }, icon: BarChart3 },
    ] },
    seller: { label: { fr: "Vendeur", en: "Seller" }, accent: "text-teal-600", accentBg: "bg-teal-500", menu: [
      { id: "dashboard", label: { fr: "Tableau de bord", en: "Dashboard" }, icon: LayoutDashboard },
      { id: "new_sale", label: { fr: "Nouvelle vente", en: "New sale" }, icon: ShoppingCart },
      { id: "sales", label: { fr: "Ventes", en: "Sales" }, icon: TrendingUp },
      { id: "customers", label: { fr: "Clients", en: "Customers" }, icon: Users },
    ] },
  },
  pharmacy: {
    admin: {
      label: { fr: "Administrateur", en: "Administrator" },
      accent: "text-emerald-600 dark:text-emerald-400",
      accentBg: "bg-emerald-500",
      menu: [
        { id: "dashboard", label: { fr: "Tableau de bord", en: "Dashboard" }, icon: LayoutDashboard },
        { id: "reports", label: { fr: "Rapports", en: "Reports" }, icon: BarChart3 },
        { id: "habits", label: { fr: "Habitudes", en: "Habits" }, icon: Target },
        { id: "members", label: { fr: "Équipe", en: "Team" }, icon: UserCheck },
        { id: "security", label: { fr: "Sécurité", en: "Security" }, icon: Shield },
        { id: "settings", label: { fr: "Paramètres", en: "Settings" }, icon: Settings },
      ],
    },
    manager: {
      label: { fr: "Manager", en: "Manager" },
      accent: "text-emerald-600 dark:text-emerald-400",
      accentBg: "bg-emerald-500",
      menu: [
        { id: "dashboard", label: { fr: "Tableau de bord", en: "Dashboard" }, icon: LayoutDashboard },
        { id: "reports", label: { fr: "Rapports", en: "Reports" }, icon: BarChart3 },
      ],
    },
    pharmacist: {
      label: { fr: "Pharmacien", en: "Pharmacist" },
      accent: "text-teal-600 dark:text-teal-400",
      accentBg: "bg-teal-500",
      menu: [
        { id: "dashboard", label: { fr: "Tableau de bord", en: "Dashboard" }, icon: LayoutDashboard },
        { id: "inventory", label: { fr: "Produits", en: "Products" }, icon: Pill },
        { id: "stocks", label: { fr: "Stock", en: "Stock" }, icon: Package },
        { id: "prescriptions", label: { fr: "Ordonnances", en: "Prescriptions" }, icon: Stethoscope },
        { id: "reports", label: { fr: "Rapports", en: "Reports" }, icon: FileText },
      ],
    },
    cashier: {
      label: { fr: "Caissier", en: "Cashier" },
      accent: "text-sky-600 dark:text-sky-400",
      accentBg: "bg-sky-500",
      menu: [
        { id: "dashboard", label: { fr: "Tableau de bord", en: "Dashboard" }, icon: LayoutDashboard },
        { id: "new_sale", label: { fr: "Nouvelle vente", en: "New sale" }, icon: ShoppingCart },
        { id: "sales", label: { fr: "Ventes", en: "Sales" }, icon: TrendingUp },
        { id: "inventory", label: { fr: "Vérifier stock", en: "Check stock" }, icon: Package },
        { id: "prescriptions", label: { fr: "Ordonnances", en: "Prescriptions" }, icon: Stethoscope },
        { id: "orders", label: { fr: "Commandes", en: "Orders" }, icon: Truck },
      ],
    },
    accountant: {
      label: { fr: "Comptable", en: "Accountant" },
      accent: "text-violet-600 dark:text-violet-400",
      accentBg: "bg-violet-500",
      menu: [
        { id: "dashboard", label: { fr: "Tableau de bord", en: "Dashboard" }, icon: LayoutDashboard },
        { id: "accounting", label: { fr: "Comptabilité", en: "Accounting" }, icon: DollarSign },
        { id: "expenses", label: { fr: "Dépenses", en: "Expenses" }, icon: TrendingUp },
        { id: "reports", label: { fr: "Rapports", en: "Reports" }, icon: FileText },
      ],
    },
    viewer: {
      label: { fr: "Observateur", en: "Observer" },
      accent: "text-slate-600 dark:text-slate-400",
      accentBg: "bg-slate-500",
      menu: [
        { id: "dashboard", label: { fr: "Tableau de bord", en: "Dashboard" }, icon: LayoutDashboard },
        { id: "inventory", label: { fr: "Produits", en: "Products" }, icon: Pill },
        { id: "reports", label: { fr: "Rapports", en: "Reports" }, icon: FileText },
      ],
    },
    teacher: { label: { fr: "Enseignant", en: "Teacher" }, accent: "text-indigo-600", accentBg: "bg-indigo-500", menu: [] },
    supervisor: { label: { fr: "Surveillant", en: "Supervisor" }, accent: "text-amber-600", accentBg: "bg-amber-500", menu: [] },
    payroll: { label: { fr: "Paie", en: "Payroll" }, accent: "text-pink-600", accentBg: "bg-pink-500", menu: [] },
    hr: {
      label: { fr: "RH", en: "HR" },
      accent: "text-cyan-600",
      accentBg: "bg-cyan-500",
      menu: [
        { id: "hr_dashboard", label: { fr: "Tableau de bord RH", en: "HR Dashboard" }, icon: LayoutDashboard },
        { id: "hr_employees", label: { fr: "Employés", en: "Employees" }, icon: Users },
        { id: "hr_recruitment", label: { fr: "Recrutement", en: "Recruitment" }, icon: UserPlus },
        { id: "hr_attendance", label: { fr: "Présence", en: "Attendance" }, icon: ClipboardCheck },
        { id: "hr_leave", label: { fr: "Congés", en: "Leave" }, icon: Plane },
        { id: "hr_absences", label: { fr: "Absences", en: "Absences" }, icon: FileWarning },
        { id: "hr_contracts", label: { fr: "Contrats", en: "Contracts" }, icon: FileCheck },
        { id: "hr_departments", label: { fr: "Départements", en: "Departments" }, icon: Building2 },
        { id: "hr_orgchart", label: { fr: "Organigramme", en: "Org Chart" }, icon: Network },
        { id: "hr_training", label: { fr: "Formations", en: "Training" }, icon: Training },
        { id: "hr_evaluations", label: { fr: "Évaluations", en: "Evaluations" }, icon: Star },
        { id: "hr_skills", label: { fr: "Compétences", en: "Skills" }, icon: Zap },
        { id: "hr_promotions", label: { fr: "Promotions", en: "Promotions" }, icon: ArrowUpRight },
        { id: "hr_discipline", label: { fr: "Discipline", en: "Discipline" }, icon: Shield },
        { id: "hr_health_safety", label: { fr: "Santé et sécurité", en: "Health & Safety" }, icon: Heart },
        { id: "hr_documents", label: { fr: "Documents RH", en: "HR Documents" }, icon: FolderOpen },
        { id: "hr_communication", label: { fr: "Communication", en: "Communication" }, icon: MessageSquare },
        { id: "hr_reports", label: { fr: "Rapports", en: "Reports" }, icon: BarChart3 },
        { id: "hr_audit_log", label: { fr: "Journal d'audit", en: "Audit Log" }, icon: Clipboard },
        { id: "hr_settings", label: { fr: "Paramètres RH", en: "HR Settings" }, icon: Sliders },
      ],
    },
    stock_manager: { label: { fr: "Gestionnaire de stock", en: "Stock Manager" }, accent: "text-orange-600", accentBg: "bg-orange-500", menu: [
      { id: "dashboard", label: { fr: "Tableau de bord", en: "Dashboard" }, icon: LayoutDashboard },
      { id: "inventory", label: { fr: "Stock", en: "Stock" }, icon: Package },
      { id: "reports", label: { fr: "Rapports", en: "Reports" }, icon: BarChart3 },
    ] },
    seller: { label: { fr: "Vendeur", en: "Seller" }, accent: "text-teal-600", accentBg: "bg-teal-500", menu: [
      { id: "dashboard", label: { fr: "Tableau de bord", en: "Dashboard" }, icon: LayoutDashboard },
      { id: "ventes", label: { fr: "Ventes", en: "Sales" }, icon: TrendingUp },
      { id: "produits", label: { fr: "Produits", en: "Products" }, icon: Package },
      { id: "customers", label: { fr: "Clients", en: "Customers" }, icon: Users },
    ] },
  },
  commerce: {
    admin: {
      label: { fr: "Administrateur", en: "Administrator" },
      accent: "text-orange-600 dark:text-orange-400",
      accentBg: "bg-orange-500",
      menu: [
        { id: "dashboard", label: { fr: "Tableau de bord", en: "Dashboard" }, icon: LayoutDashboard },
        { id: "reports", label: { fr: "Rapports", en: "Reports" }, icon: BarChart3 },
        { id: "habits", label: { fr: "Habitudes", en: "Habits" }, icon: Target },
        { id: "members", label: { fr: "Équipe", en: "Team" }, icon: UserCheck },
        { id: "security", label: { fr: "Sécurité", en: "Security" }, icon: Shield },
        { id: "settings", label: { fr: "Paramètres", en: "Settings" }, icon: Settings },
      ],
    },
    manager: {
      label: { fr: "Manager", en: "Manager" },
      accent: "text-orange-600 dark:text-orange-400",
      accentBg: "bg-orange-500",
      menu: [
        { id: "dashboard", label: { fr: "Tableau de bord", en: "Dashboard" }, icon: LayoutDashboard },
        { id: "reports", label: { fr: "Rapports", en: "Reports" }, icon: BarChart3 },
      ],
    },
    cashier: {
      label: { fr: "Caissier", en: "Cashier" },
      accent: "text-sky-600 dark:text-sky-400",
      accentBg: "bg-sky-500",
      menu: [
        { id: "dashboard", label: { fr: "Tableau de bord", en: "Dashboard" }, icon: LayoutDashboard },
        { id: "ventes", label: { fr: "Ventes", en: "Sales" }, icon: TrendingUp },
        { id: "produits", label: { fr: "Produits", en: "Products" }, icon: Package },
        { id: "history", label: { fr: "Historique", en: "History" }, icon: Clock },
      ],
    },
    accountant: {
      label: { fr: "Comptable", en: "Accountant" },
      accent: "text-violet-600 dark:text-violet-400",
      accentBg: "bg-violet-500",
      menu: [
        { id: "dashboard", label: { fr: "Tableau de bord", en: "Dashboard" }, icon: LayoutDashboard },
        { id: "ventes", label: { fr: "Ventes", en: "Sales" }, icon: TrendingUp },
        { id: "comptabilite", label: { fr: "Comptabilité", en: "Accounting" }, icon: DollarSign },
        { id: "reports", label: { fr: "Rapports", en: "Reports" }, icon: FileText },
      ],
    },
    viewer: {
      label: { fr: "Observateur", en: "Observer" },
      accent: "text-slate-600 dark:text-slate-400",
      accentBg: "bg-slate-500",
      menu: [
        { id: "dashboard", label: { fr: "Tableau de bord", en: "Dashboard" }, icon: LayoutDashboard },
        { id: "produits", label: { fr: "Produits", en: "Products" }, icon: Package },
        { id: "reports", label: { fr: "Rapports", en: "Reports" }, icon: FileText },
      ],
    },
    teacher: { label: { fr: "Enseignant", en: "Teacher" }, accent: "text-indigo-600", accentBg: "bg-indigo-500", menu: [] },
    supervisor: { label: { fr: "Surveillant", en: "Supervisor" }, accent: "text-amber-600", accentBg: "bg-amber-500", menu: [] },
    pharmacist: { label: { fr: "Pharmacien", en: "Pharmacist" }, accent: "text-teal-600", accentBg: "bg-teal-500", menu: [] },
    payroll: { label: { fr: "Paie", en: "Payroll" }, accent: "text-pink-600", accentBg: "bg-pink-500", menu: [] },
    hr: {
      label: { fr: "RH", en: "HR" },
      accent: "text-cyan-600",
      accentBg: "bg-cyan-500",
      menu: [
        { id: "hr_dashboard", label: { fr: "Tableau de bord RH", en: "HR Dashboard" }, icon: LayoutDashboard },
        { id: "hr_employees", label: { fr: "Employés", en: "Employees" }, icon: Users },
        { id: "hr_recruitment", label: { fr: "Recrutement", en: "Recruitment" }, icon: UserPlus },
        { id: "hr_attendance", label: { fr: "Présence", en: "Attendance" }, icon: ClipboardCheck },
        { id: "hr_leave", label: { fr: "Congés", en: "Leave" }, icon: Plane },
        { id: "hr_absences", label: { fr: "Absences", en: "Absences" }, icon: FileWarning },
        { id: "hr_contracts", label: { fr: "Contrats", en: "Contracts" }, icon: FileCheck },
        { id: "hr_departments", label: { fr: "Départements", en: "Departments" }, icon: Building2 },
        { id: "hr_orgchart", label: { fr: "Organigramme", en: "Org Chart" }, icon: Network },
        { id: "hr_training", label: { fr: "Formations", en: "Training" }, icon: Training },
        { id: "hr_evaluations", label: { fr: "Évaluations", en: "Evaluations" }, icon: Star },
        { id: "hr_skills", label: { fr: "Compétences", en: "Skills" }, icon: Zap },
        { id: "hr_promotions", label: { fr: "Promotions", en: "Promotions" }, icon: ArrowUpRight },
        { id: "hr_discipline", label: { fr: "Discipline", en: "Discipline" }, icon: Shield },
        { id: "hr_health_safety", label: { fr: "Santé et sécurité", en: "Health & Safety" }, icon: Heart },
        { id: "hr_documents", label: { fr: "Documents RH", en: "HR Documents" }, icon: FolderOpen },
        { id: "hr_communication", label: { fr: "Communication", en: "Communication" }, icon: MessageSquare },
        { id: "hr_reports", label: { fr: "Rapports", en: "Reports" }, icon: BarChart3 },
        { id: "hr_audit_log", label: { fr: "Journal d'audit", en: "Audit Log" }, icon: Clipboard },
        { id: "hr_settings", label: { fr: "Paramètres RH", en: "HR Settings" }, icon: Sliders },
      ],
    },
    stock_manager: { label: { fr: "Stock", en: "Stock" }, accent: "text-orange-600", accentBg: "bg-orange-500", menu: [] },
    seller: { label: { fr: "Vendeur", en: "Seller" }, accent: "text-teal-600", accentBg: "bg-teal-500", menu: [] },
  },
  gestion: {
    admin: {
      label: { fr: "Administrateur", en: "Administrator" },
      accent: "text-purple-600 dark:text-purple-400",
      accentBg: "bg-purple-500",
      menu: [
        { id: "dashboard", label: { fr: "Tableau de bord", en: "Dashboard" }, icon: LayoutDashboard },
        { id: "employees", label: { fr: "Employés", en: "Employees" }, icon: Briefcase },
        { id: "payments", label: { fr: "Paiements", en: "Payments" }, icon: DollarSign },
        { id: "accounting", label: { fr: "Comptabilité", en: "Accounting" }, icon: Receipt },
        { id: "reports", label: { fr: "Rapports", en: "Reports" }, icon: BarChart3 },
        { id: "members", label: { fr: "Équipe", en: "Team" }, icon: UserCheck },
        { id: "security", label: { fr: "Sécurité", en: "Security" }, icon: Shield },
        { id: "settings", label: { fr: "Paramètres", en: "Settings" }, icon: Settings },
      ],
    },
    manager: {
      label: { fr: "Manager", en: "Manager" },
      accent: "text-purple-600 dark:text-purple-400",
      accentBg: "bg-purple-500",
      menu: [
        { id: "dashboard", label: { fr: "Tableau de bord", en: "Dashboard" }, icon: LayoutDashboard },
        { id: "reports", label: { fr: "Rapports", en: "Reports" }, icon: BarChart3 },
      ],
    },
    accountant: {
      label: { fr: "Comptable", en: "Accountant" },
      accent: "text-violet-600 dark:text-violet-400",
      accentBg: "bg-violet-500",
      menu: [
        { id: "dashboard", label: { fr: "Tableau de bord", en: "Dashboard" }, icon: LayoutDashboard },
        { id: "accounting", label: { fr: "Comptabilité", en: "Accounting" }, icon: DollarSign },
        { id: "reports", label: { fr: "Rapports", en: "Reports" }, icon: FileText },
      ],
    },
    cashier: {
      label: { fr: "Caissier", en: "Cashier" },
      accent: "text-emerald-600 dark:text-emerald-400",
      accentBg: "bg-emerald-500",
      menu: [
        { id: "dashboard", label: { fr: "Tableau de bord", en: "Dashboard" }, icon: LayoutDashboard },
        { id: "payments", label: { fr: "Paiements", en: "Payments" }, icon: CreditCard },
        { id: "history", label: { fr: "Historique", en: "History" }, icon: Clock },
      ],
    },
    viewer: {
      label: { fr: "Observateur", en: "Observer" },
      accent: "text-slate-600 dark:text-slate-400",
      accentBg: "bg-slate-500",
      menu: [
        { id: "dashboard", label: { fr: "Tableau de bord", en: "Dashboard" }, icon: LayoutDashboard },
        { id: "reports", label: { fr: "Rapports", en: "Reports" }, icon: FileText },
      ],
    },
    teacher: { label: { fr: "Enseignant", en: "Teacher" }, accent: "text-indigo-600", accentBg: "bg-indigo-500", menu: [] },
    supervisor: { label: { fr: "Surveillant", en: "Supervisor" }, accent: "text-amber-600", accentBg: "bg-amber-500", menu: [] },
    pharmacist: { label: { fr: "Pharmacien", en: "Pharmacist" }, accent: "text-teal-600", accentBg: "bg-teal-500", menu: [] },
    payroll: {
      label: { fr: "Paie", en: "Payroll" },
      accent: "text-pink-600",
      accentBg: "bg-pink-500",
      menu: [
        { id: "dashboard", label: { fr: "Tableau de bord", en: "Dashboard" }, icon: LayoutDashboard },
        { id: "payments", label: { fr: "Paiements", en: "Payments" }, icon: CreditCard },
        { id: "history", label: { fr: "Historique", en: "History" }, icon: Clock },
        { id: "reports", label: { fr: "Rapports", en: "Reports" }, icon: FileText },
      ],
    },
    hr: {
      label: { fr: "RH", en: "HR" },
      accent: "text-cyan-600",
      accentBg: "bg-cyan-500",
      menu: [
        { id: "hr_dashboard", label: { fr: "Tableau de bord RH", en: "HR Dashboard" }, icon: LayoutDashboard },
        { id: "hr_employees", label: { fr: "Employés", en: "Employees" }, icon: Users },
        { id: "hr_recruitment", label: { fr: "Recrutement", en: "Recruitment" }, icon: UserPlus },
        { id: "hr_attendance", label: { fr: "Présence", en: "Attendance" }, icon: ClipboardCheck },
        { id: "hr_leave", label: { fr: "Congés", en: "Leave" }, icon: Plane },
        { id: "hr_absences", label: { fr: "Absences", en: "Absences" }, icon: FileWarning },
        { id: "hr_contracts", label: { fr: "Contrats", en: "Contracts" }, icon: FileCheck },
        { id: "hr_departments", label: { fr: "Départements", en: "Departments" }, icon: Building2 },
        { id: "hr_orgchart", label: { fr: "Organigramme", en: "Org Chart" }, icon: Network },
        { id: "hr_training", label: { fr: "Formations", en: "Training" }, icon: Training },
        { id: "hr_evaluations", label: { fr: "Évaluations", en: "Evaluations" }, icon: Star },
        { id: "hr_skills", label: { fr: "Compétences", en: "Skills" }, icon: Zap },
        { id: "hr_promotions", label: { fr: "Promotions", en: "Promotions" }, icon: ArrowUpRight },
        { id: "hr_discipline", label: { fr: "Discipline", en: "Discipline" }, icon: Shield },
        { id: "hr_health_safety", label: { fr: "Santé et sécurité", en: "Health & Safety" }, icon: Heart },
        { id: "hr_documents", label: { fr: "Documents RH", en: "HR Documents" }, icon: FolderOpen },
        { id: "hr_communication", label: { fr: "Communication", en: "Communication" }, icon: MessageSquare },
        { id: "hr_reports", label: { fr: "Rapports", en: "Reports" }, icon: BarChart3 },
        { id: "hr_audit_log", label: { fr: "Journal d'audit", en: "Audit Log" }, icon: Clipboard },
        { id: "hr_settings", label: { fr: "Paramètres RH", en: "HR Settings" }, icon: Sliders },
      ],
    },
    stock_manager: { label: { fr: "Gestionnaire de stock", en: "Stock Manager" }, accent: "text-orange-600", accentBg: "bg-orange-500", menu: [
      { id: "dashboard", label: { fr: "Tableau de bord", en: "Dashboard" }, icon: LayoutDashboard },
      { id: "inventory", label: { fr: "Inventaire", en: "Inventory" }, icon: Package },
      { id: "reports", label: { fr: "Rapports", en: "Reports" }, icon: BarChart3 },
    ] },
    seller: { label: { fr: "Vendeur", en: "Seller" }, accent: "text-teal-600", accentBg: "bg-teal-500", menu: [
      { id: "dashboard", label: { fr: "Tableau de bord", en: "Dashboard" }, icon: LayoutDashboard },
      { id: "payments", label: { fr: "Paiements", en: "Payments" }, icon: CreditCard },
      { id: "reports", label: { fr: "Rapports", en: "Reports" }, icon: FileText },
    ] },
  },
  hr: {
    admin: {
      label: { fr: "Administrateur RH", en: "HR Administrator" },
      accent: "text-sky-600 dark:text-sky-400",
      accentBg: "bg-sky-500",
      menu: [
        { id: "dashboard", label: { fr: "Tableau de bord", en: "Dashboard" }, icon: LayoutDashboard },
        { id: "hr_employees", label: { fr: "Employés", en: "Employees" }, icon: Users },
        { id: "hr_recruitment", label: { fr: "Recrutement", en: "Recruitment" }, icon: UserPlus },
        { id: "hr_attendance", label: { fr: "Présence", en: "Attendance" }, icon: ClipboardCheck },
        { id: "hr_leave", label: { fr: "Congés", en: "Leave" }, icon: Plane },
        { id: "hr_contracts", label: { fr: "Contrats", en: "Contracts" }, icon: FileCheck },
        { id: "hr_departments", label: { fr: "Départements", en: "Departments" }, icon: Building2 },
        { id: "hr_training", label: { fr: "Formations", en: "Training" }, icon: Training },
        { id: "hr_evaluations", label: { fr: "Évaluations", en: "Evaluations" }, icon: Star },
        { id: "hr_reports", label: { fr: "Rapports", en: "Reports" }, icon: BarChart3 },
        { id: "members", label: { fr: "Équipe", en: "Team" }, icon: UserCheck },
        { id: "security", label: { fr: "Sécurité", en: "Security" }, icon: Shield },
        { id: "settings", label: { fr: "Paramètres", en: "Settings" }, icon: Settings },
      ],
    },
    manager: {
      label: { fr: "Manager RH", en: "HR Manager" },
      accent: "text-sky-600 dark:text-sky-400",
      accentBg: "bg-sky-500",
      menu: [
        { id: "dashboard", label: { fr: "Tableau de bord", en: "Dashboard" }, icon: LayoutDashboard },
        { id: "hr_employees", label: { fr: "Employés", en: "Employees" }, icon: Users },
        { id: "hr_leave", label: { fr: "Congés", en: "Leave" }, icon: Plane },
        { id: "hr_attendance", label: { fr: "Présence", en: "Attendance" }, icon: ClipboardCheck },
        { id: "hr_evaluations", label: { fr: "Évaluations", en: "Evaluations" }, icon: Star },
        { id: "hr_reports", label: { fr: "Rapports", en: "Reports" }, icon: BarChart3 },
      ],
    },
    employee: {
      label: { fr: "Employé", en: "Employee" },
      accent: "text-sky-600 dark:text-sky-400",
      accentBg: "bg-sky-500",
      menu: [
        { id: "dashboard", label: { fr: "Tableau de bord", en: "Dashboard" }, icon: LayoutDashboard },
        { id: "hr_leave", label: { fr: "Mes congés", en: "My Leave" }, icon: Plane },
        { id: "hr_documents", label: { fr: "Mes documents", en: "My Documents" }, icon: FileCheck },
      ],
    },
    accountant: { label: { fr: "Comptable", en: "Accountant" }, accent: "text-sky-600", accentBg: "bg-sky-500", menu: [] },
    cashier: { label: { fr: "Caissier", en: "Cashier" }, accent: "text-sky-600", accentBg: "bg-sky-500", menu: [] },
    supervisor: { label: { fr: "Superviseur", en: "Supervisor" }, accent: "text-sky-600", accentBg: "bg-sky-500", menu: [] },
    viewer: {
      label: { fr: "Observateur", en: "Observer" },
      accent: "text-slate-600",
      accentBg: "bg-slate-500",
      menu: [
        { id: "dashboard", label: { fr: "Tableau de bord", en: "Dashboard" }, icon: LayoutDashboard },
      ],
    },
    pharmacist: { label: { fr: "Pharmacien", en: "Pharmacist" }, accent: "text-sky-600", accentBg: "bg-sky-500", menu: [] },
    teacher: { label: { fr: "Enseignant", en: "Teacher" }, accent: "text-sky-600", accentBg: "bg-sky-500", menu: [] },
    stock_manager: { label: { fr: "Stock", en: "Stock" }, accent: "text-sky-600", accentBg: "bg-sky-500", menu: [] },
    seller: { label: { fr: "Vendeur", en: "Seller" }, accent: "text-sky-600", accentBg: "bg-sky-500", menu: [] },
  },
}

export const WORKSPACE_TYPE_LABELS: Record<WorkspaceType, { fr: string; en: string }> = {
  education: { fr: "Éducation", en: "Education" },
  pharmacy: { fr: "Pharmacie", en: "Pharmacy" },
  commerce: { fr: "Commerce", en: "Commerce" },
  gestion: { fr: "Gestion", en: "Management" },
  hr: { fr: "Ressources Humaines", en: "Human Resources" },
}
