[auth]
require_email_verification = false
verify_email_method = "code"
reset_password_method = "code"
disable_signup = false

[auth.password]
min_length = 6
require_number = false
require_lowercase = false
require_uppercase = false
require_special_char = false

[auth.smtp]
enabled = true
host = "smtp.zoho.com"
port = 587
username = "243-857599332.627@zohomail.com"
password = "env(SMTP_PASSWORD)"
sender_email = "243-857599332.627@zohomail.com"
sender_name = "SaveMali"
min_interval_seconds = 60

[storage]
max_file_size_mb = 100

[realtime]

[schedules]
retention_days = 7